### ISSUE TITLE
Lock On Doesn't Work in 1.18.2

### ISSUE THREAD

**Issue by InteJason** [Tfarcenim/LockOn#2]
Forge: 40.1.84
Minecraft Version: 1.18.2

I can't get the lock on to work. I have adjusted keybinds and fixed overlapping keybinds. I saw that 1.19 got a fix "Don't register null keybindings". Is it possible to port the fix to 1.18 as well? Cuz as of right now it's completely non-functional :/ Many thanks!

**Comment by Mgazul** [comment]
I tested 1.19.2 and it still doesn't work

**Comment by BugmanBugman** [comment]
Doesn't seem to be working 1.20.1

**Comment by BugmanBugman** [comment]
Nvm, got it to work
